### ISSUE TITLE
Implement `loop_control` for noisy tasks

### ISSUE THREAD

**Issue by savchenko** [savchenko/debian#48]
```yaml
      with_items: '{{ something.results }}'
      loop_control:
        label: "{{ item.short_key }}"
```
